# Generated by Django 3.2.6 on 2021-08-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='exclamation',
            field=models.CharField(choices=[('Hallo', 'German'), ('Hello', 'English'), ('Tgau', 'Romontsch'), ('Ciao', 'Italian')], default='Hello', max_length=32),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
