# Generated by Django 3.2.6 on 2021-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210809_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='exclamation',
            field=models.CharField(blank=True, choices=[('Hallo', 'German'), ('Hello', 'English'), ('Tgau', 'Romontsch'), ('Ciao', 'Italian')], default=None, max_length=32, null=True),
        ),
    ]
